"""
Visualization Tool - Generate interactive ECharts for financial data
"""
import os
import json
from datetime import datetime
from langchain.tools import tool
from coze_coding_dev_sdk.s3 import S3SyncStorage


def _generate_echarts_html(company_name: str, ticker: str, chart_data: dict) -> str:
    """Generate ECharts HTML with financial visualization"""
    timeline = chart_data.get("timeline", [])
    revenue = chart_data.get("revenue", [])
    net_income = chart_data.get("net_income", [])
    fcf = chart_data.get("fcf", [])
    gross_margin = chart_data.get("gross_margin", [])
    operating_margin = chart_data.get("operating_margin", [])
    net_margin = chart_data.get("net_margin", [])
    revenue_growth = chart_data.get("revenue_growth", [])

    years = [str(y) for y in timeline]
    years_json = json.dumps(years)
    revenue_json = json.dumps(revenue)
    net_income_json = json.dumps(net_income)
    fcf_json = json.dumps(fcf)
    gross_margin_json = json.dumps(gross_margin)
    operating_margin_json = json.dumps(operating_margin)
    net_margin_json = json.dumps(net_margin)
    revenue_growth_json = json.dumps(revenue_growth)

    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{company_name} Financial Analysis</title>
    <script src="https://cdn.jsdelivr.net/npm/echarts@5.4.3/dist/echarts.min.js"></script>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0a0a0a; color: #fff; padding: 20px; }}
        .header {{ text-align: center; margin-bottom: 30px; }}
        .header h1 {{ font-size: 28px; color: #00ff88; margin-bottom: 8px; }}
        .header p {{ color: #888; font-size: 14px; }}
        .chart-container {{ background: #1a1a2e; border-radius: 16px; padding: 20px; margin-bottom: 20px; box-shadow: 0 4px 20px rgba(0,255,136,0.1); }}
        .chart {{ height: 350px; }}
        .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(400px, 1fr)); gap: 20px; }}
        .footer {{ text-align: center; color: #555; font-size: 12px; margin-top: 30px; }}
        .disclaimer {{ background: rgba(255,165,0,0.1); border: 1px solid rgba(255,165,0,0.3); border-radius: 8px; padding: 15px; margin-top: 20px; color: #ffa500; font-size: 12px; text-align: center; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{company_name} ({ticker})</h1>
        <p>Financial Analysis Dashboard | NEPV Sector</p>
    </div>
    
    <div class="grid">
        <div class="chart-container">
            <h3 style="margin-bottom:15px;color:#00ff88;">📈 Revenue & Net Income Trend</h3>
            <div id="chart1" class="chart"></div>
        </div>
        
        <div class="chart-container">
            <h3 style="margin-bottom:15px;color:#00ff88;">💰 Free Cash Flow</h3>
            <div id="chart2" class="chart"></div>
        </div>
        
        <div class="chart-container">
            <h3 style="margin-bottom:15px;color:#00ff88;">📊 Profitability Margins</h3>
            <div id="chart3" class="chart"></div>
        </div>
        
        <div class="chart-container">
            <h3 style="margin-bottom:15px;color:#00ff88;">📉 YoY Revenue Growth Rate</h3>
            <div id="chart4" class="chart"></div>
        </div>
    </div>
    
    <div class="disclaimer">
        ⚠️ This analysis is for educational and internal research purposes only. Not investment advice.
    </div>
    
    <div class="footer">
        Generated by NEPV Equity Research Agent | Data: Sample FY2020-FY2024
    </div>

    <script>
        var years = {years_json};
        var revenue = {revenue_json};
        var netIncome = {net_income_json};
        var fcf = {fcf_json};
        var grossMargin = {gross_margin_json};
        var operatingMargin = {operating_margin_json};
        var netMargin = {net_margin_json};
        var revenueGrowth = {revenue_growth_json};

        // Chart 1: Revenue & Net Income
        var chart1 = echarts.init(document.getElementById('chart1'));
        chart1.setOption({{
            tooltip: {{ trigger: 'axis', backgroundColor: 'rgba(0,0,0,0.8)', borderColor: '#00ff88', textStyle: {{ color: '#fff' }} }},
            legend: {{ data: ['Revenue', 'Net Income'], textStyle: {{ color: '#888' }} }},
            grid: {{ left: '3%', right: '4%', bottom: '3%', containLabel: true }},
            xAxis: {{ type: 'category', data: years, axisLine: {{ lineStyle: {{ color: '#333' }} }}, axisLabel: {{ color: '#888' }} }},
            yAxis: {{ type: 'value', name: 'Million CNY', axisLine: {{ lineStyle: {{ color: '#333' }} }}, axisLabel: {{ color: '#888', formatter: '{{value}}' }}, splitLine: {{ lineStyle: {{ color: '#222' }} }} }},
            series: [
                {{ name: 'Revenue', type: 'bar', data: revenue, itemStyle: {{ color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{{offset: 0, color: '#00ff88'}}, {{offset: 1, color: '#0088ff'}}]) }}, label: {{ show: true, position: 'top', color: '#888', formatter: '{{c}}' }} }},
                {{ name: 'Net Income', type: 'line', yAxisIndex: 0, data: netIncome, smooth: true, lineStyle: {{ color: '#ff6b6b', width: 3 }}, itemStyle: {{ color: '#ff6b6b' }} }}
            ]
        }});

        // Chart 2: Free Cash Flow
        var chart2 = echarts.init(document.getElementById('chart2'));
        chart2.setOption({{
            tooltip: {{ trigger: 'axis', backgroundColor: 'rgba(0,0,0,0.8)', borderColor: '#00ff88', textStyle: {{ color: '#fff' }} }},
            grid: {{ left: '3%', right: '4%', bottom: '3%', containLabel: true }},
            xAxis: {{ type: 'category', data: years, axisLine: {{ lineStyle: {{ color: '#333' }} }}, axisLabel: {{ color: '#888' }} }},
            yAxis: {{ type: 'value', name: 'Million CNY', axisLine: {{ lineStyle: {{ color: '#333' }} }}, axisLabel: {{ color: '#888' }}, splitLine: {{ lineStyle: {{ color: '#222' }} }} }},
            series: [{{
                name: 'FCF', type: 'bar', data: fcf,
                itemStyle: {{ color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{{offset: 0, color: '#ffd700'}}, {{offset: 1, color: '#ff8c00'}}]) }},
                label: {{ show: true, position: 'top', color: '#888' }}
            }}]
        }});

        // Chart 3: Profitability Margins
        var chart3 = echarts.init(document.getElementById('chart3'));
        chart3.setOption({{
            tooltip: {{ trigger: 'axis', backgroundColor: 'rgba(0,0,0,0.8)', borderColor: '#00ff88', textStyle: {{ color: '#fff' }}, formatter: function(params) {{ var res = params[0].name; params.forEach(function(p) {{ res += '<br/>' + p.marker + p.seriesName + ': ' + p.value + '%'; }}); return res; }} }},
            legend: {{ data: ['Gross', 'Operating', 'Net'], textStyle: {{ color: '#888' }} }},
            grid: {{ left: '3%', right: '4%', bottom: '3%', containLabel: true }},
            xAxis: {{ type: 'category', data: years, axisLine: {{ lineStyle: {{ color: '#333' }} }}, axisLabel: {{ color: '#888' }} }},
            yAxis: {{ type: 'value', name: '%', axisLine: {{ lineStyle: {{ color: '#333' }} }}, axisLabel: {{ color: '#888', formatter: '{{value}}%' }}, splitLine: {{ lineStyle: {{ color: '#222' }} }} }},
            series: [
                {{ name: 'Gross', type: 'line', data: grossMargin, smooth: true, lineStyle: {{ color: '#00ff88', width: 3 }}, itemStyle: {{ color: '#00ff88' }} }},
                {{ name: 'Operating', type: 'line', data: operatingMargin, smooth: true, lineStyle: {{ color: '#0088ff', width: 3 }}, itemStyle: {{ color: '#0088ff' }} }},
                {{ name: 'Net', type: 'line', data: netMargin, smooth: true, lineStyle: {{ color: '#ff6b6b', width: 3 }}, itemStyle: {{ color: '#ff6b6b' }} }}
            ]
        }});

        // Chart 4: YoY Growth Rate
        var chart4 = echarts.init(document.getElementById('chart4'));
        chart4.setOption({{
            tooltip: {{ trigger: 'axis', backgroundColor: 'rgba(0,0,0,0.8)', borderColor: '#00ff88', textStyle: {{ color: '#fff' }}, formatter: '{{c[0].name}}<br/><span style="color:#ffd700">●</span> Growth: {{c[0].value}}%' }},
            grid: {{ left: '3%', right: '4%', bottom: '3%', containLabel: true }},
            xAxis: {{ type: 'category', data: years.slice(1), axisLine: {{ lineStyle: {{ color: '#333' }} }}, axisLabel: {{ color: '#888' }} }},
            yAxis: {{ type: 'value', name: '%', axisLine: {{ lineStyle: {{ color: '#333' }} }}, axisLabel: {{ color: '#888', formatter: '{{value}}%' }}, splitLine: {{ lineStyle: {{ color: '#222' }} }} }},
            series: [{{
                name: 'Revenue Growth',
                type: 'bar',
                data: revenueGrowth,
                itemStyle: {{
                    color: function(params) {{
                        return params.value >= 0 ? '#00ff88' : '#ff4444';
                    }}
                }},
                label: {{ show: true, position: 'top', color: '#888', formatter: '{{c.value}}%' }}
            }}]
        }});

        // Responsive
        window.addEventListener('resize', function() {{
            chart1.resize();
            chart2.resize();
            chart3.resize();
            chart4.resize();
        }});
    </script>
</body>
</html>"""
    return html


@tool
def generate_visualization(
    company_name: str,
    ticker: str,
    chart_data_json: str
) -> str:
    """
    Generate interactive ECharts visualization for financial data.
    
    Args:
        company_name: Company name (e.g., "BYD Company Limited")
        ticker: Stock ticker (e.g., "BYD")
        chart_data_json: JSON string with financial data including:
            - timeline: List of years
            - revenue: List of revenue values
            - net_income: List of net income values
            - fcf: List of free cash flow values
            - gross_margin: List of gross margin percentages
            - operating_margin: List of operating margin percentages
            - net_margin: List of net margin percentages
            - revenue_growth: List of YoY growth rates
    
    Returns:
        URL to view the interactive chart
    """
    try:
        chart_data = json.loads(chart_data_json)
    except json.JSONDecodeError:
        return "Error: Invalid chart_data_json format. Please provide valid JSON string."
    
    html_content = _generate_echarts_html(company_name, ticker, chart_data)
    
    # Upload to object storage
    try:
        storage = S3SyncStorage(
            endpoint_url=os.getenv("COZE_BUCKET_ENDPOINT_URL"),
            access_key="",
            secret_key="",
            bucket_name=os.getenv("COZE_BUCKET_NAME"),
            region="cn-beijing",
        )
        
        file_name = f"charts/{ticker}_financial_{datetime.now().strftime('%Y%m%d%H%M%S')}.html"
        key = storage.upload_file(
            file_content=html_content.encode('utf-8'),
            file_name=file_name,
            content_type="text/html",
        )
        
        url = storage.generate_presigned_url(key=key, expire_time=86400)
        
        return f"""📊 **Interactive Chart Generated!**

**Company:** {company_name} ({ticker})

**View Charts:** {url}

Charts include:
- 📈 Revenue & Net Income Trend
- 💰 Free Cash Flow Analysis
- 📊 Profitability Margins (Gross/Operating/Net)
- 📉 Year-over-Year Growth Rates

⚠️ For educational purposes only, not investment advice."""

    except Exception as e:
        # Fallback: save locally if storage fails
        local_path = f"/tmp/{ticker}_financial_analysis.html"
        with open(local_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return f"""📊 **Chart Generated (Local)**

**Company:** {company_name} ({ticker})

Note: Chart saved locally due to storage error. Please use the preview mode to view charts.

Charts include:
- 📈 Revenue & Net Income Trend
- 💰 Free Cash Flow Analysis
- 📊 Profitability Margins
- 📉 YoY Growth Rates

⚠️ For educational purposes only."""


@tool
def generate_dcf_sensitivity_chart(
    company_name: str,
    ticker: str,
    base_value_per_share: str,
    wacc_range: str,
    terminal_growth_range: str
) -> str:
    """
    Generate DCF sensitivity analysis heatmap.
    
    Args:
        company_name: Company name
        ticker: Stock ticker
        base_value_per_share: Base DCF value per share
        wacc_range: Comma-separated WACC values (e.g., "8,9,10,11,12")
        terminal_growth_range: Comma-separated terminal growth rates (e.g., "2,2.5,3")
    
    Returns:
        URL to view the sensitivity heatmap
    """
    try:
        wacc_values = [float(x.strip()) for x in wacc_range.split(',')]
        tg_values = [float(x.strip()) for x in terminal_growth_range.split(',')]
        base_val = float(base_value_per_share)
        
        # Generate sensitivity matrix
        matrix = []
        for tg in reversed(tg_values):
            row = []
            for wacc in wacc_values:
                ratio = (1 + tg) / (wacc / 100 - tg)
                row.append(round(base_val * ratio / (1 + wacc / 100), 2))
            matrix.append(row)
        
        matrix_json = json.dumps(matrix)
        wacc_json = json.dumps(wacc_values)
        tg_json = json.dumps(list(reversed(tg_values)))
        
        html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>DCF Sensitivity Analysis - {company_name}</title>
    <script src="https://cdn.jsdelivr.net/npm/echarts@5.4.3/dist/echarts.min.js"></script>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0a0a0a; color: #fff; padding: 20px; }}
        .container {{ max-width: 800px; margin: 0 auto; }}
        .header {{ text-align: center; margin-bottom: 30px; }}
        .header h1 {{ font-size: 24px; color: #00ff88; }}
        .chart-container {{ background: #1a1a2e; border-radius: 16px; padding: 20px; box-shadow: 0 4px 20px rgba(0,255,136,0.1); }}
        .chart {{ height: 400px; }}
        .info {{ background: rgba(0,255,136,0.1); border-radius: 8px; padding: 15px; margin-top: 20px; }}
        .disclaimer {{ background: rgba(255,165,0,0.1); border: 1px solid rgba(255,165,0,0.3); border-radius: 8px; padding: 15px; margin-top: 20px; color: #ffa500; font-size: 12px; text-align: center; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{company_name} ({ticker}) - DCF Sensitivity</h1>
            <p>Value Per Share (CNY) | Base: {base_value_per_share}</p>
        </div>
        
        <div class="chart-container">
            <div id="chart" class="chart"></div>
        </div>
        
        <div class="info">
            <strong>Reading Guide:</strong><br/>
            - Columns: WACC (Discount Rate)<br/>
            - Rows: Terminal Growth Rate<br/>
            - Green: Higher value | Red: Lower value
        </div>
        
        <div class="disclaimer">
            ⚠️ Sensitivity analysis for educational purposes. Not investment advice.
        </div>
    </div>

    <script>
        var data = {matrix_json};
        var waccValues = {wacc_json};
        var tgValues = {tg_json};

        var chart = echarts.init(document.getElementById('chart'));
        chart.setOption({{
            tooltip: {{
                position: 'top',
                backgroundColor: 'rgba(0,0,0,0.9)',
                borderColor: '#00ff88',
                textStyle: {{ color: '#fff' }},
                formatter: function(params) {{
                    return 'WACC: ' + waccValues[params.data[0]] + '%<br/>' +
                           'Terminal Growth: ' + tgValues[params.data[1]] + '%<br/>' +
                           'Value: ¥' + params.data[2].toFixed(2);
                }}
            }},
            grid: {{ left: '3%', right: '8%', bottom: '15%', containLabel: true }},
            xAxis: {{
                type: 'category',
                data: waccValues.map(function(v) {{ return v + '%'; }}),
                axisLine: {{ lineStyle: {{ color: '#333' }} }},
                axisLabel: {{ color: '#888' }},
                name: 'WACC',
                nameLocation: 'middle',
                nameGap: 30
            }},
            yAxis: {{
                type: 'category',
                data: tgValues.map(function(v) {{ return v + '%'; }}),
                axisLine: {{ lineStyle: {{ color: '#333' }} }},
                axisLabel: {{ color: '#888' }},
                name: 'Terminal Growth',
                nameLocation: 'middle',
                nameGap: 50
            }},
            visualMap: {{
                min: {base_val * 0.5},
                max: {base_val * 2},
                calculable: true,
                orient: 'horizontal',
                left: 'center',
                bottom: '0%',
                inRange: {{
                    color: ['#ff4444', '#ff8844', '#ffcc44', '#88ff44', '#00ff88']
                }},
                textStyle: {{ color: '#888' }}
            }},
            series: [{{
                name: 'Value',
                type: 'heatmap',
                data: data.map(function(row, i) {{
                    return row.map(function(val, j) {{ return [j, i, val]; }});
                }}).reduce(function(acc, cur) {{ return acc.concat(cur); }}, []),
                label: {{
                    show: true,
                    color: '#000',
                    fontWeight: 'bold',
                    formatter: function(params) {{
                        return params.data[2].toFixed(0);
                    }}
                }},
                emphasis: {{
                    itemStyle: {{ shadowBlur: 10, shadowColor: 'rgba(0, 255, 136, 0.5)' }}
                }}
            }}]
        }});

        window.addEventListener('resize', function() {{ chart.resize(); }});
    </script>
</body>
</html>"""
        
        # Upload to storage
        storage = S3SyncStorage(
            endpoint_url=os.getenv("COZE_BUCKET_ENDPOINT_URL"),
            access_key="",
            secret_key="",
            bucket_name=os.getenv("COZE_BUCKET_NAME"),
            region="cn-beijing",
        )
        
        file_name = f"charts/{ticker}_dcf_sensitivity_{datetime.now().strftime('%Y%m%d%H%M%S')}.html"
        key = storage.upload_file(
            file_content=html.encode('utf-8'),
            file_name=file_name,
            content_type="text/html",
        )
        
        url = storage.generate_presigned_url(key=key, expire_time=86400)
        
        return f"""🔥 **DCF Sensitivity Heatmap Generated!**

**Company:** {company_name} ({ticker})
**Base Value:** ¥{base_value_per_share} per share

**View Sensitivity Chart:** {url}

Parameters:
- WACC Range: {wacc_range}%
- Terminal Growth: {terminal_growth_range}%

⚠️ For educational purposes only, not investment advice."""

    except Exception as e:
        return f"Error generating sensitivity chart: {str(e)}"
